version: "3"
services:
  pa:
    image: xanderxaj/planetary-annihilation-server
    build: .
    user: 1000:1000
    env_file:
      - .env
    volumes:
      - ./pa:/opt/pa:rw
    ports:
      - 20545:20545/tcp
